findstr /s /r /i /m /c:"\<angal.admission.deletem\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.editm\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.youaresigningnewdatawithyournameconfirm\>" *.*
findstr /s /r /i /m /c:"\<angal.common.codemaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.common.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.dicom.manager.nodir\>" *.*
findstr /s /r /i /m /c:"\<angal.dicom.manager.noimpl\>" *.*
findstr /s /r /i /m /c:"\<angal.dlvrrestype.codetoolongmaxchar\>" *.*
findstr /s /r /i /m /c:"\<angal.exatype.codetoolongmaxchar\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.delete\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.edit\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.new\>" *.*
findstr /s /r /i /m /c:"\<angal.malnutrition.controldatemustbeaftervisitdate\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.delete\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.edit\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.new\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.problemsoccurredwithsqlistruction\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.insertvalidweight\>" *.*
findstr /s /r /i /m /c:"\<angal.medstockmovtype.codetoolongmaxchar\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.btn.laboratoryresulttype\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.laboratoryresulttype\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.delete\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.disease1mayhavebeencanceled\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.disease2mayhavebeencanceled\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.disease3mayhavebeencanceled\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.edit\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.new\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.addressm\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.agem\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.citym\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.namem\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.sexm\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.telephonem\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.delete\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.edit\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.new\>" *.*
findstr /s /r /i /m /c:"\<angal.preagtreattype.codemaxlength\>" *.*
findstr /s /r /i /m /c:"\<angal.preagtreattype.codetoolong\>" *.*
findstr /s /r /i /m /c:"\<angal.preagtreattype.description2\>" *.*
findstr /s /r /i /m /c:"\<angal.priceslist.descriptionstar\>" *.*