findstr /s /r /i /m /c:"\<angal.admission.address\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.admissionnotes\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.deleteadmission\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.diagnosisin\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.diagnosisoutsameasdiagnosisin\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.editadmission\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.education\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.filtering\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.levelis\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.levelisunknown\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.newunitis\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.newweightis\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.newweightwillbe\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.newweightwillbenull\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.oldweightis\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.operationm\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.parsingnewweight\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.patientmustbeafemale\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidabortdatebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidadmissiondate\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidcontroln1datebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidcontroln2datebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavaliddeliverydatebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavaliddischargedate\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidoperationdate\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidoperationdatebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidvisitdatebetween\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseinsertavalidweightvaluemust\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseselectatleastfirstdiagnosisin\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.pleaseselectpatient\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.poor\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.rich\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.select\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.status\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.stop\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.theselectedadmissionhasnoconcernwithmalnutrit\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.wardis\>" *.*
findstr /s /r /i /m /c:"\<angal.admission.weneed\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.agetypeedit\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.child\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.deleterow\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.editingagetyperecord\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.newagetyperecord\>" *.*
findstr /s /r /i /m /c:"\<angal.agetype.pleaseinsertadescription\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.billalreadyclosed\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.from\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.openbillsreport\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.openedbillslist\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.pleaseselectamonth\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.to\>" *.*
findstr /s /r /i /m /c:"\<angal.billbrowser.update\>" *.*
findstr /s /r /i /m /c:"\<angal.common.descriptionstar\>" *.*
findstr /s /r /i /m /c:"\<angal.common.todaym\>" *.*
findstr /s /r /i /m /c:"\<angal.common.uom.meter\>" *.*
findstr /s /r /i /m /c:"\<angal.dicom.image.patient.surname\>" *.*
findstr /s /r /i /m /c:"\<angal.dicom.noconn\>" *.*
findstr /s /r /i /m /c:"\<angal.dicomtype.codem\>" *.*
findstr /s /r /i /m /c:"\<angal.dicomtype.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.dicomtype.youcannotdeletethisrecord\>" *.*
findstr /s /r /i /m /c:"\<angal.disctype.codemaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.disease.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.disease.select\>" *.*
findstr /s /r /i /m /c:"\<angal.dlvrrestype.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.exa.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.exa.select\>" *.*
findstr /s /r /i /m /c:"\<angal.examination.auscultation.unknown\>" *.*
findstr /s /r /i /m /c:"\<angal.examination.hemoglucosetest\>" *.*
findstr /s /r /i /m /c:"\<angal.exatype.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.errorreleasingconnection\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.errorrollbackingconnection\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.exporttopdffile\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.from\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.greaterthan\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.high\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.laboratoryprinting\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.lessthan\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.low\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.negative\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.notreactive\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.openwithjasperReport\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.printreport\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.reactive\>" *.*
findstr /s /r /i /m /c:"\<angal.lab.to\>" *.*
findstr /s /r /i /m /c:"\<angal.labnew.examhasbeenchangedwouldyouliketosavechanges\>" *.*
findstr /s /r /i /m /c:"\<angal.labnew.pleaseinsertadate\>" *.*
findstr /s /r /i /m /c:"\<angal.labnew.selectamaterial\>" *.*
findstr /s /r /i /m /c:"\<angal.labnew.selectanexam\>" *.*
findstr /s /r /i /m /c:"\<angal.labnew.selectaresult\>" *.*
findstr /s /r /i /m /c:"\<angal.malnutrition.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.malnutrition.heightandweight\>" *.*
findstr /s /r /i /m /c:"\<angal.malnutrition.lastcontrol\>" *.*
findstr /s /r /i /m /c:"\<angal.malnutrition.select\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.import\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.insertavalidvalue\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.pcsperpck\>" *.*
findstr /s /r /i /m /c:"\<angal.medicals.select\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.bottlesorboxes\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.buttons\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.chooseanalreadyexistentlot\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.chooseapharmaceutical\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.chooseasupplier\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.chooseaward\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.currentquantitylyinginstock\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.from\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.insertanewlot\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.insertavalidlotidentifier\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.inserttheexpirydate\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.inserttheoriginofthepharmaceutical\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.insertthepreparationdate\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.jms\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.lotpanel\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.movementdatefromcannotbelaterthanmovementd\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.movementtypechargedischarge\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.movementtypecodenotvalid\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.movementtypedescriptionnotvalid\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.movementtypetypenotvalid\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multiplecharging.chooseasupplier\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multiplecharging.notallowed\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.datebeforelastmovement\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.futuredatenotallowed\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.lotid\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.notallowed\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.pleaseinsertareferencenumber\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.preparationdate\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.theinsertedreferencenumberalreadyexists\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.totalcost\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.multipledischarging.unitcost\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.notspecified\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.noward\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.piecesorml\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.pleaseselectalotorcreateanewone\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.preparationdatefromcannotbelaterpreparatio\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.refnom\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.reset\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.searchcode\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.select\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.table\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.thetotalquantitycannotbelessthan\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.to\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstock.unitcost\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.doyoureallywanttodeletethismovement\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.from\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.outcome.destination\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.patient\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.expiringdateinthepastnotallowed\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.futuredatenotallowed\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.lotid\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.qty\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.referencenumber\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectify.totalcost\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.rectifyerror\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockward.to\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.insertquantitypiecesormls\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.instock\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.invalidproduct\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.invalidquantity\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.invalidquantitypleaseinsertatleast\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.invalidquantitypleaseinsertmax\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.invalidquantitypleasetryagain\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.pleaseinsertavalidquantity\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.productalreadyinserted\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.selectamedical\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.theselectedpatienthasnoweightdefined\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.tooltip.changethepatientassociatedwiththismovement\>" *.*
findstr /s /r /i /m /c:"\<angal.medicalstockwardedit.updateageandweightforthispatient\>" *.*
findstr /s /r /i /m /c:"\<angal.medstockmovtype.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.medstockmovtype.pleaseinsertavalidtype\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.btn.therapy\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.menuitemmainmenu\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.passwdm\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.type\>" *.*
findstr /s /r /i /m /c:"\<angal.menu.visits\>" *.*
findstr /s /r /i /m /c:"\<angal.newbill.failedtosavebill\>" *.*
findstr /s /r /i /m /c:"\<angal.newbill.pleaseselectapaymentfirst\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.patientsearch\>" *.*
findstr /s /r /i /m /c:"\<angal.opd.progyearm\>" *.*
findstr /s /r /i /m /c:"\<angal.operation.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.operation.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.operation.select\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.agetooltip\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.economicstatus\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.educationlevel\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.father\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.heightandweight\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.merge.title\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.mother\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.nowebcamfound\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.poor\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.quality\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.rich\>" *.*
findstr /s /r /i /m /c:"\<angal.patient.toproceedyouneedtosavecontinue\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.from\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.patientdata\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.printtable\>" *.*
findstr /s /r /i /m /c:"\<angal.patvac.to\>" *.*
findstr /s /r /i /m /c:"\<angal.preagtreattype.codemaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.preagtreattype.codetoolongmaxchars\>" *.*
findstr /s /r /i /m /c:"\<angal.priceslist.acurrency\>" *.*
findstr /s /r /i /m /c:"\<angal.priceslist.aname\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.billid\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.byreduction.title\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.byuser.title\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.lastpayment\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.notpaid\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.paid\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.patient\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.title\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.to\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.to2\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreport.totals\>" *.*
findstr /s /r /i /m /c:"\<angal.report.billsreportuserallindate.date\>" *.*
findstr /s /r /i /m /c:"\<angal.report.patientbillextended.discount\>" *.*
findstr /s /r /i /m /c:"\<angal.report.patientbillpaymentstxt.balance\>" *.*
findstr /s /r /i /m /c:"\<angal.sql.couldntfindthedataithasprobablybeendeleted\>" *.*
findstr /s /r /i /m /c:"\<angal.sql.thedataisnomorepresent\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.patienttherapiescouldnotbesaved\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.patienttherapiessaved\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.startingdate\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.therapiesplanhasnotbeensavedsaveandclose\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.therapytitle\>" *.*
findstr /s /r /i /m /c:"\<angal.therapy.visitedate\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.childm\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.notpregnantm\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.patientcategory\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.pregnantm\>" *.*
findstr /s /r /i /m /c:"\<angal.vaccine.select\>" *.*
findstr /s /r /i /m /c:"\<angal.video.devices\>" *.*
findstr /s /r /i /m /c:"\<angal.video.pausestream\>" *.*
findstr /s /r /i /m /c:"\<angal.video.rescanresolutions\>" *.*
findstr /s /r /i /m /c:"\<angal.video.resolution\>" *.*
findstr /s /r /i /m /c:"\<angal.video.resumestream\>" *.*
findstr /s /r /i /m /c:"\<angal.video.setfullscreen\>" *.*
findstr /s /r /i /m /c:"\<angal.video.shootaphoto\>" *.*
findstr /s /r /i /m /c:"\<angal.visit.visitfor\>" *.*
findstr /s /r /i /m /c:"\<angal.visit.visittomorrow\>" *.*
findstr /s /r /i /m /c:"\<angal.ward.doyouwanttooverwritethedata\>" *.*
findstr /s /r /i /m /c:"\<angal.ward.pattern.patientsarestilladmittedinward\>" *.*
findstr /s /r /i /m /c:"\<angal.ward.pleaseinsertaname\>" *.*
